CREATE TABLE `coupon_transaction` (
  `id` int NOT NULL AUTO_INCREMENT,
  `type` varchar(20) NOT NULL,
  `status` int NOT NULL,
  `utc_timestamp` datetime NOT NULL,
  `coupon_id` int DEFAULT NULL,
  `coupon_serial` bigint(20) DEFAULT NULL,
  `pos_token` varchar(32) DEFAULT NULL,
  `pos_restaurant` varchar(6) DEFAULT NULL,
  `pos_terminal` varchar(50) DEFAULT NULL,
  `pos_operator` varchar(50) DEFAULT NULL,
  `pos_transid` varchar(20) DEFAULT NULL,
  `pos_timestamp` datetime DEFAULT NULL,
  `pos_language` varchar(2) DEFAULT NULL,
  `coupon_code_raw` varchar(100) DEFAULT NULL,
  `coupon_code` varchar(45) DEFAULT NULL,
  `coupon_secret_hash` varchar(32) DEFAULT NULL,
  `coupon_expiration_hash` varchar(32) DEFAULT NULL,
  `basket_type` varchar(20) DEFAULT NULL,
  `basket_items` text,
  `basket_coupon_amount` decimal(9,2) DEFAULT NULL,
  `basket_coupon_retail_amount` decimal(9,2) DEFAULT NULL,
  `basket_taxes` decimal(9,2) DEFAULT NULL,
  `basket_total` decimal(9,2) DEFAULT NULL,
  `basket_discounted_plu` varchar(500) DEFAULT NULL,
  `basket_discounted_category` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_UNIQUE` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=165280 DEFAULT CHARSET=utf8mb4;
